//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Banderoll
    {
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "ИД Почтового отправления")]
        public int IDPostItem { get; set; }
        [Display(Name = "Заказное")]
        public bool Registered { get; set; }
        [Display(Name = "Объявленная ценность")]
        public decimal DeclaredValue { get; set; }
        [Display(Name = "Вес")]
        public string Weight { get; set; }
        [Display(Name = "Ширина")]
        public int Width { get; set; }
        [Display(Name = "Длина")]
        public int Length { get; set; }
        [Display(Name = "Высоота")]
        public int Height { get; set; }
    
        public virtual PostItem PostItem { get; set; }
    }
}
