//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Notice
    {
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "Дата извещения")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfNotification { get; set; }
        [Display(Name = "Повторное извещение")]
        public bool SecondNotice { get; set; }
    
        public virtual PostItem PostItem { get; set; }
    }
}
