//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Packing
    {
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "Тип упаковки")]
        public string TypePacking { get; set; }
        [Display(Name = "Цена")]
        public decimal Cost { get; set; }
        [Display(Name = "Количество")]
        public int Count { get; set; }
        [Display(Name = "ИД Продажи")]
        public int IDSaleOfGoods { get; set; }
    
        public virtual SaleOfGoods SaleOfGoods { get; set; }
    }
}
