//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PensionPayment
    {
        [Display(Name = "ИД Выплаты")]
        public int IDPayment { get; set; }
        [Display(Name = "ИД Пенсионера")]
        public int IDPensioner { get; set; }
        [Display(Name = "Дата выплаты")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DataPayment { get; set; }
        [Display(Name = "Сумма пенсии")]
        public decimal Payout { get; set; }
        [Display(Name = "ИД Работника")]
        public int IDWorker { get; set; }
    
        public virtual Pensioner Pensioner { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
