//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Pensioner
    {
        public Pensioner()
        {
            this.PensionPayment = new HashSet<PensionPayment>();
        }
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "Имя")]
        public string FirstName { get; set; }
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
        [Display(Name = "Отчество")]
        public string SecondName { get; set; }
        [Display(Name = "Адрес")]
        public string Adrress { get; set; }
        [Display(Name = "Почтовый индекс")]
        public int PostIndex { get; set; }
        [Display(Name = "Серия паспорта")]
        public int SeriesOfPassport { get; set; }
        [Display(Name = "Номер паспорта")]
        public int NumberOfPassport { get; set; }
    
        public virtual PostOffice PostOffice { get; set; }
        public virtual ICollection<PensionPayment> PensionPayment { get; set; }
    }
}
