//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PostItem
    {
        public PostItem()
        {
            this.BagM = new HashSet<BagM>();
            this.Banderoll = new HashSet<Banderoll>();
            this.Letter = new HashSet<Letter>();
            this.Posilka = new HashSet<Posilka>();
            this.PostalContainer = new HashSet<PostalContainer>();
            this.PostCard = new HashSet<PostCard>();
            this.Secogramma = new HashSet<Secogramma>();
            this.SmallPacket = new HashSet<SmallPacket>();
        }
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "ИД Работника")]
        public int IDWorker { get; set; }
        [Display(Name = "Отправитель")]
        public string Sender { get; set; }
        [Display(Name = "Адрес отправителя")]
        public string SenderAddress { get; set; }
        [Display(Name = "Адрес полуателя")]
        public string RecipientAddress { get; set; }
        [Display(Name = "Тип отправления")]
        public string TypeDeparture { get; set; }
        [Display(Name = "Стоимость отправления")]
        public decimal CostOfSending { get; set; }
        [Display(Name = "Статус почтового отправления")]
        public string StatusOfMandate { get; set; }
        [Display(Name = "Наложенный платеж")]
        public bool CashOnDelivery { get; set; }
        [Display(Name = "Цена нал. платежа")]
        public Nullable<decimal> PriceCOD { get; set; }
        [Display(Name = "Получение/Отправление")]
        public bool SentReceived { get; set; }
        [Display(Name = "Отказ получения")]
        public bool FailureObtaining { get; set; }
    
        public virtual ICollection<BagM> BagM { get; set; }
        public virtual ICollection<Banderoll> Banderoll { get; set; }
        public virtual ICollection<Letter> Letter { get; set; }
        public virtual Notice Notice { get; set; }
        public virtual ICollection<Posilka> Posilka { get; set; }
        public virtual ICollection<PostalContainer> PostalContainer { get; set; }
        public virtual ICollection<PostCard> PostCard { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<Secogramma> Secogramma { get; set; }
        public virtual ICollection<SmallPacket> SmallPacket { get; set; }
    }
}
