//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SaleOfGoods
    {
        public SaleOfGoods()
        {
            this.Brand = new HashSet<Brand>();
            this.Packing = new HashSet<Packing>();
        }
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "Время покупки")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime TimeOfPurchase { get; set; }
        [Display(Name = "Итоговая цена")]
        public decimal TotalPrice { get; set; }
        [Display(Name = "Количество товара")]
        public int NumberOfPurchasedGoods { get; set; }
        [Display(Name = "ИД Работника")]
        public int IDWorker { get; set; }
    
        public virtual ICollection<Brand> Brand { get; set; }
        public virtual ICollection<Packing> Packing { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
