//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice2013_KharitonovAlexey.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Worker
    {
        public Worker()
        {
            this.FeedbackOnTheWorker = new HashSet<FeedbackOnTheWorker>();
            this.PensionPayment = new HashSet<PensionPayment>();
            this.PostItem = new HashSet<PostItem>();
            this.SaleOfGoods = new HashSet<SaleOfGoods>();
        }
        [Display(Name = "ИД")]
        public int ID { get; set; }
        [Display(Name = "Имя")]
        public string FirstName { get; set; }
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
        [Display(Name = "Отчество")]
        public string SecondName { get; set; }
        [Display(Name = "Адрес")]
        public string Adrress { get; set; }
        [Display(Name = "Индекс")]
        public int PostIndex { get; set; }
        [Display(Name = "Стаж работы")]
        public string LengthOfWork { get; set; }
        [Display(Name = "Дата принятия")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfEmployment { get; set; }
        [Display(Name = "Плата")]
        public decimal Wages { get; set; }
        [Display(Name = "Должность")]
        public string Post { get; set; }
    
        public virtual ICollection<FeedbackOnTheWorker> FeedbackOnTheWorker { get; set; }
        public virtual ICollection<PensionPayment> PensionPayment { get; set; }
        public virtual ICollection<PostItem> PostItem { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual ICollection<SaleOfGoods> SaleOfGoods { get; set; }
    }
}
